apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitor-agent
spec:
  selector:
    matchLabels:
      name: monitor-agent
  template:
    metadata:
      labels:
        name: monitor-agent
    spec:
      containers:
      - name: agent
        image: busybox
        command: ["sh", "-c", "while true; do echo Monitoring node...; sleep 60; done"]
